### ISSUE TITLE
Installation error on windows using local clone with stable version, Missing TH.h

### ISSUE THREAD

**Issue by tradenity** [facebookresearch/pytorch3d#1122] opened 2022-03-14 12:59 UTC
Hi

I am trying to install on windows with the following configuration

Windows 10
using conda environment
python 3.7
pytorch3d stable branch
pytorch=1.11.0
cudatoolkit=11.3 (I have RTX 3060 card)
CUB_HOME set correctly with lib source ver. 1.16.0
MSVC setup correctly
removed c++14 references from setup.py

When I run setup install or pip install -e .
I get the following error

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Joseph\.conda\envs\adnerf\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Joseph\\Documents\\development\\startups\\genesis\\prototyping\\AD-NeRF\\pytorch3d\\setup.py'"'"'; __file__='"'"'C:\\Users\\Joseph\\Documents\\development\\startups\\genesis\\prototyping\\AD-NeRF\\pytorch3d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\
    Complete output (6394 lines):
    running develop
    running egg_info
    creating pytorch3d.egg-info
    writing pytorch3d.egg-info\PKG-INFO
    writing dependency_links to pytorch3d.egg-info\dependency_links.txt
    writing requirements to pytorch3d.egg-info\requires.txt
    writing top-level names to pytorch3d.egg-info\top_level.txt
    writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
    reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
    running build_ext
    building 'pytorch3d._C' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\Users
    creating build\temp.win-amd64-3.7\Release\Users\Joseph
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\ball_query
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\blending
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\compositing
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\face_areas_normals
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\gather_scatter
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\iou_box3d
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\knn
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\mesh_normal_consistency
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\packed_to_padded_tensor
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\points_to_volumes
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\point_mesh
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\pulsar
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\pulsar\host
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\pulsar\pytorch
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\rasterize_meshes
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\rasterize_points
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\sample_farthest_points
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\sample_pdf
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\interp_face_attrs
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\pulsar\cuda
    creating build\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\rasterize_coarse
    E:\Programs\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -IC:\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc -IC:\Users\Joseph\Documents\development\devkits\cuba\1.16.0 -IC:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include -IC:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\TH -IC:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\THC -IC:\Users\Joseph\.conda\envs\adnerf\Library\include -IC:\Users\Joseph\.conda\envs\adnerf\include -IC:\Users\Joseph\.conda\envs\adnerf\include "-IE:\Programs\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\ATLMFC\include" "-IE:\Programs\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /TpC:\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\ext.cpp /Fobuild\temp.win-amd64-3.7\Release\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\ext.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
    ext.cpp
    C:\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\./pulsar/global.h(46): warning C4068: unknown pragma 'clang'
    C:\Users\Joseph\Documents\development\startups\genesis\prototyping\AD-NeRF\pytorch3d\pytorch3d\csrc\./pulsar/global.h(47): warning C4068: unknown pragma 'clang'
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/macros/Macros.h(142): warning C4067: unexpected tokens following preprocessor directive - expected a newline
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/util/Optional.h(198): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
            with
            [
                T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
            ]
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/util/Optional.h(397): note: see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
            with
            [
                T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
            ]
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/util/Optional.h(540): note: see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
            with
            [
                T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
            ]
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/util/Optional.h(540): note: see reference to alias template instantiation 'c10::OptionalBase<c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>>' being compiled
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/core/impl/InlineDeviceGuard.h(427): note: see reference to class template instantiation 'c10::optional<c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>>' being compiled
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/core/DeviceGuard.h(178): note: see reference to class template instantiation 'c10::impl::InlineOptionalDeviceGuard<c10::impl::VirtualGuardImpl>' being compiled
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/util/Optional.h(432): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
            with
            [
                T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
            ]
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/util/Optional.h(198): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
            with
            [
                T=at::TensorBase
            ]
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\c10/util/Optional.h(397): note: see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
```

```
 C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: 'HAVE_SNPRINTF': macro redefinition
    C:\Users\Joseph\.conda\envs\adnerf\include\pyerrors.h(490): note: see previous definition of 'HAVE_SNPRINTF'
    C:\AD-NeRF\pytorch3d\pytorch3d\csrc\pulsar\include\../global.h(49): warning C4068: unknown pragma 'clang'
    C:\AD-NeRF\pytorch3d\pytorch3d\csrc\pulsar\include\./commands.h(30): warning C4068: unknown pragma 'clang'
    C:\AD-NeRF\pytorch3d\pytorch3d\csrc\pulsar\include\./commands.h(31): warning C4068: unknown pragma 'clang'
    C:\AD-NeRF\pytorch3d\pytorch3d\csrc\pulsar\include\./commands.h(32): fatal error C1083: Cannot open include file: 'TH/TH.h': No such file or directory
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\utils\cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\utils\cpp_extension.py:322: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\torch\utils\cpp_extension.py:788: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
      warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
    error: command 'E:\\Programs\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Users\Joseph\.conda\envs\adnerf\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
ERROR: Command errored out with exit status 1: 'C:\Users\Joseph\.conda\envs\adnerf\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\AD-NeRF\\pytorch3d\\setup.py'"'"'; __file__='"'"'C:\\AD-NeRF\\pytorch3d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
It looks like it cannot find Th\TH.h file

Thanks

**Comment by bottler** [comment] 2022-03-14 13:56
Yes. Since the last release (0.6.1 = current stable) that file was removed from PyTorch's main branch and that change has last week been released as part of PyTorch 1.11. You can't build pytorch3d stable with PyTorch 1.11. 

In PyTorch, there are fixes on the main branch ( f8fe9a2be144cf3c7c047e05d59605474f3a8bdb and 069c9fd759461b60f089dd01f6779f9437a5695f ) which happened since the last release and preserve ongoing compatibility with PyTorch.

You can build 0.6.1 with a version of PyTorch it was designed for, or use the main branch of PyTorch3D.

**Comment by tradenity** [comment] 2022-03-14 14:46
Then you mean I can use pytorch 1.11.0 with current master branch (HEAD revision) of pytorch3d?

**Comment by bottler** [comment] 2022-03-14 14:58
Yes, the `main` branch.

**Closed** 2022-03-15 13:28 UTC
Labels: installation

**Comment by YaroslavShchekaturov** [comment] 2023-03-09 01:47
Hi @bottler I'm currently trying to install Pytorch3d with pytorch 1.11.0 but for some reason I cannot find TH.h files 
![image](https://user-images.githubusercontent.com/22734034/223894248-eee1c0d6-395b-43c4-89b8-ab7060c021f1.png)

**Comment by bottler** [comment] 2023-03-09 13:27
@YaroslavShchekaturov If you still need help, please open a new issue and explain more what you have done.
