### ISSUE TITLE
Bug in `_C. point_face_dist_forward`

### ISSUE THREAD

**Issue by Sentient07** [facebookresearch/pytorch3d#897] opened 2021-10-23 10:52 UTC
## 🐛 Bugs / Unexpected behaviors

Hello. I'm trying to compute the closest face of a point in 3D to a mesh. My mesh is watertight. I observed discrepancy between Trimesh's [closest point](https://trimsh.org/trimesh.proximity.html#trimesh.proximity.closest_point) and pytorch3d. To test this, I sampled points on the surface of the mesh while preserving the information on the face where the point was sampled from. When I try to check the closest faceID by calling `_C.point_face_dist_forward` method, the observed face indices differs from where I originally sampled. Below is my code that you can reproduce on a registered mesh from FAUST dataset. I attempted across 50 runs and Pytorch3d's implementation is roughly only 97% accurate. 

```

def get_pt_mesh_dist(src_mesh, mesh_coord):
    m_t3d = Meshes(verts=[torch.from_numpy(np.array(src_mesh.vertices)).cuda().float()],
                   faces=[torch.from_numpy(np.array(src_mesh.faces)).cuda()])
    pcl = Pointclouds(points=[torch.from_numpy(mesh_coord).cuda().float()])
    points = pcl.points_packed()
    points_first_idx = pcl.cloud_to_packed_first_idx()
    max_points = pcl.num_points_per_cloud().max().item()
    verts_packed = m_t3d.verts_packed()
    faces_packed = m_t3d.faces_packed()
    tris = verts_packed[faces_packed]
    tris_first_idx = m_t3d.mesh_to_faces_packed_first_idx()
    _, idxs = _C.point_face_dist_forward(points.float(), points_first_idx, tris.float(), tris_first_idx, max_points)
    return idxs

src_mesh = trimesh.load('/mnt/disk1/datasets/MPI-FAUST/training/registrations/tr_reg_090.ply', process=False)
surface_pts, fid_tm = src_mesh.sample(100000, return_index=True)
fid_pyt3d = get_pt_mesh_dist(src_mesh, surface_pts).cpu().numpy()
print(src_mesh.is_watertight)
np.allclose(fid_tm, fid_pyt3d), (fid_pyt3d != fid_tm).sum()
```

Is this behaviour expected? If so, can you please elaborate the intuition behind? Thank you

**Comment by nikhilaravi** [comment] 2021-11-15 23:07
@Sentient07 do you still need help with this issue?

**Comment by gkioxari** [comment] 2021-11-17 04:53
@Sentient07 I'd love to help with this but we cannot reproduce your code. You are not providing the data for us to reproduce the issue.

**Comment by Sentient07** [comment] 2021-11-18 10:34
Hello. Thanks for your reply. Yes, I'm curious about this issue. The mesh I demonstrate the above code is using the FAUST dataset. Since their copyright is not fully clear to me, I cannot send the sample here. Instead, I request you to download from their official website : https://dfaust.is.tue.mpg.de/download.php to reproduce my first comment.

However, I observe similar results with a different water-tight mesh from the remeshed-FAUST dataset. For example, please use this mesh https://github.com/llorz/SGA18_orientation_BCICP_dataset/blob/master/Dataset/FAUST/vtx_5k/tr_reg_049.off and try the code below. At my end, I observe 1.8% inaccuracy with pytorch3d

```
import pytorch3d
from pytorch3d.structures.meshes import Meshes
from pytorch3d.structures.pointclouds import Pointclouds
from pytorch3d import _C
from pytorch3d.loss import point_mesh_face_distance
from pytorch3d.loss.point_mesh_distance import point_face_distance, point_edge_distance
def get_pt_mesh_dist(src_mesh, mesh_coord):
    m_t3d = Meshes(verts=[torch.from_numpy(np.array(src_mesh.vertices)).cuda().float()],
                   faces=[torch.from_numpy(np.array(src_mesh.faces)).cuda()])
    pcl = Pointclouds(points=[torch.from_numpy(mesh_coord).cuda().float()])
    points = pcl.points_packed()
    points_first_idx = pcl.cloud_to_packed_first_idx()
    max_points = pcl.num_points_per_cloud().max().item()
    verts_packed = m_t3d.verts_packed()
    faces_packed = m_t3d.faces_packed()
    tris = verts_packed[faces_packed]
    tris_first_idx = m_t3d.mesh_to_faces_packed_first_idx()
    _, idxs = _C.point_face_dist_forward(points.float(), points_first_idx, tris.float(), tris_first_idx, max_points)
    return idxs

src_mesh = trimesh.load('/mnt/disk1/datasets/SGA18_orientation_BCICP_dataset/Dataset/FAUST/vtx_5k/tr_reg_049.off', process=False)
surface_pts, fid_tm = src_mesh.sample(100000, return_index=True)
fid_pyt3d = get_pt_mesh_dist(src_mesh, surface_pts).cpu().numpy()
print(src_mesh.is_watertight)
np.allclose(fid_tm, fid_pyt3d), (fid_pyt3d != fid_tm).sum()
```

**Comment by gkioxari** [comment] 2021-11-18 20:58
I looked into the issue and here is the explanation. In short, the sampling operation is not invertible and here is why. 

Assume you have two adjacent faces. You sample a point from the first face, which with some probability ends up at the edge of the face with its neighbor. Now, if you compute the distance of that sampled point to the two faces it's very close to 0 for both and any method will return the index by resolving a tie. 

You can verify this in your case easily, as follows
```python
dist_array = _C.point_face_array_dist_forward(points, tris)
```
returns the `(P,F)` matrix with the distance of each point to each face. 
If `i` and `j` are the face indices returned from trimesh and pytorch3d, respectively, for point `p`, you can check the actual distance values by looking up `dist_array[p, i]` and `dist_array[p, j]`. They are close to 0 (for me they were around 1e-15). For such small values, braking ties will not guarantee to return the same results even across platforms. But most importantly, face `j` is the right answer and face `i` is the right answer. So our op is not wrong.

**Closed** 2021-11-22 16:21 UTC
Labels: question
