### ISSUE TITLE
Result of `point_mesh_face_distance` is not agnostic to face index order

### ISSUE THREAD

**Issue by yangze0930** [facebookresearch/pytorch3d#682] opened 2021-05-19 02:01 UTC
## 🐛 Bugs / Unexpected behaviours
I'm trying to use `point_mesh_face_distance` to compute distance between point cloud and mesh. And found that the result is not agnostic to mesh face index order.

## Instructions To Reproduce the Issue:
To reproduce the bug, please run following code:
```
import torch
from pytorch3d.structures import Meshes, Pointclouds
from pytorch3d.loss import point_mesh_face_distance

mesh_vertices = torch.tensor([
    [-0.0021, -0.3769, 0.7146],
    [-0.0161, -0.3771, 0.7146],
    [-0.0021, -0.3771, 0.7147]
])
mesh1_faces = torch.tensor([[0, 2, 1]])
mesh2_faces = torch.tensor([[2, 0, 1]])
pcd_points = torch.tensor([[-0.3623, -0.5340, 0.7727]])
mesh1 = Meshes(verts=[mesh_vertices], faces=[mesh1_faces])
mesh2 = Meshes(verts=[mesh_vertices], faces=[mesh2_faces])
pcd = Pointclouds(points=[pcd_points])
loss1 = point_mesh_face_distance(mesh1, pcd)
print(loss1)
loss2 = point_mesh_face_distance(mesh2, pcd)
print(loss2)
assert loss1 == loss2, "point_mesh_face_distance should be agnostic to face index order."
```
What you observed (including the full logs):
```
tensor(0.0005)
tensor(0.2957)
AssertionError: point_mesh_face_distance should be agnostic to face index order.
```
The `mesh1` and `mesh2` only differ in face index order, so we should expect `loss1 == loss2`.

**Comment by nikhilaravi** [comment] 2021-05-19 21:24
Thank you for providing the code to reproduce this issue. When the vertex positions are changed, this behaviour is not observed so it might be due to the vertices in this example being very close to one another. We are looking into this further to see what is causing the error.

**Comment by gkioxari** [comment] 2021-06-19 11:37
Fixed by https://github.com/facebookresearch/pytorch3d/commit/88f5d790886b26efb9f370fb9e1ea2fa17079d19

The issue is because of the small faces which make some computations unstable. It is fixed now.

**Closed by gkioxari** 2021-06-19 11:37 UTC
Labels: potential-bug
