### ISSUE TITLE
multiple light sources for a single rendering

### ISSUE THREAD

**Issue by ajhamdi** [facebookresearch/pytorch3d#485] opened 2020-12-15 13:17 UTC
is it possible to add **multiple** light sources in the same scene rendering a single image by the `pytorch3d.renderer.MeshRenderer` class?

**Comment by nikhilaravi** [comment] 2020-12-16 17:06
Hi @ajhamdi, currently we don't have support for this feature!

**Comment by nikhilaravi** [comment] 2020-12-18 14:49
This is a duplicate of #241. I'll close this task - please follow the discussion on the other task.

**Closed by nikhilaravi** 2020-12-18 14:49 UTC
Labels: enhancement, how to
