### ISSUE TITLE
Installation with anaconda cloud fails

### ISSUE THREAD

**Issue by Hemantr05** [facebookresearch/pytorch3d#38] opened 2020-02-10 09:17 UTC
`conda install pytorch3d -c pytorch3d` 

gives the below output:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

**Comment by bottler** [comment] 2020-02-10 10:34
Which operating system are you on? Can you please paste the output of `conda list`. Thanks

**Comment by Hemantr05** [comment] 2020-02-11 07:34
> Which operating system are you on? Can you please paste the output of `conda list`? Thanks

Ubuntu 18.04 is the OS I'm on.


![image](https://user-images.githubusercontent.com/29824145/74217968-fd9b2a80-4cce-11ea-955b-c6608200140a.png)

**Comment by bottler** [comment] 2020-02-11 11:34
The conda environment is totally empty (as shown by `conda list`). I would expect, in that case, `conda install -c pytorch pytorch torchvision cudatoolkit=10.0` to install python and other things, and that's what happens for me. Once this has failed, there is no chance of being able to install `pytorch3d`.

Does `conda install python` work? Do you have other conda environments where python is working? If not, then I think you have a problem with conda. Updating/reinstalling anaconda might help. For example, conda uses the `pycosat` library to work out what to install, which has some versions which were behaving strangely. It might be interesting to do `conda activate` (to go back to the base) then `python -c 'import pycosat; pycosat.__version__'`. If it is less than 0.6.3 then that might be it.

**Comment by Hemantr05** [comment] 2020-02-11 13:26
I have pytorch and torchvision installed in my environment. (If you see the first line of the screenshot)
And as you can see, cuda==9.1 was installed.

And yes, conda install python works

The issue might be due the cuda version.

**Comment by bottler** [comment] 2020-02-11 13:49
I don't see pytorch and torchvision installed in the first line of the screenshot. I see a failed attempt to install them. `Segmentation fault (core dumped)` means there was a catastrophic error, and in this case I expect nothing has been done to the environment by this command. That's why I'm suspicious of your conda installation.

`conda list` is showing that there is nothing installed in the environment.

If you can install python, it might be worth trying to install the other packages one by one. I would start with `conda install cudatoolkit=9.2`.

It is true that cuda 9.1 which I think you have on your machine is too old for pytorch3d. I think this should not matter if you install a newer version of the cudatoolkit conda package (say 9.2 or 10.0), as long as your nvidia driver is new enough. I am less worried about the UnsatisfiableError than about the Segmentation Fault.

**Comment by Hemantr05** [comment] 2020-02-12 06:34
The screenshots below show the output of `conda list`, and includes pytorch as well.

![Screenshot from 2020-02-12 12-02-28](https://user-images.githubusercontent.com/29824145/74308986-a27d3c80-4d8f-11ea-8689-2d2d33a640d1.png)


![Screenshot from 2020-02-12 12-02-16](https://user-images.githubusercontent.com/29824145/74308969-9d1ff200-4d8f-11ea-8796-d10264a04f0c.png)
![Screenshot from 2020-02-12 12-02-23](https://user-images.githubusercontent.com/29824145/74308982-a0b37900-4d8f-11ea-922b-85f337ad87f9.png)
![Screenshot from 2020-02-12 12-02-20](https://user-images.githubusercontent.com/29824145/74308979-9f824c00-4d8f-11ea-92e6-7565735844ec.png)

**Comment by bottler** [comment] 2020-02-12 11:05
Thanks. That's (most of) the output of `conda list` in your base environment. It has a lot of packages, including pytorch 1.3.1 which is too old for pytorch3d. It makes sense that (like in your first message) it fails with `Found conflicts!` or similar.

In your second message I see part of an attempt to install in a different environment, called `pytorch3d`. What I said in my previous message will still apply to that environment (and the conda installation which governs it).

**Comment by Hemantr05** [comment] 2020-02-13 08:43
Will check on it, and get back.

**Comment by nikhilaravi** [comment] 2020-02-24 06:36
@Hemantr05 were you able to resolve this problem? If so, please comment with what you needed to do to resolve it so other people can also benefit! Then, please close this issue.

**Comment by raincrash** [comment] 2020-02-28 09:35
Weirdly, I had the same issue as well on OSX 10.15.3. `conda install` on `pytorch3d` channel returns a `PackagesNotFoundError`.  I'm running miniconda3 with conda version 4.8.2. Is there some dependecy of the build on cudatoolkit, because the machine I tried is CPU only. I could install it from source though.

**Comment by raincrash** [comment] 2020-02-28 10:16
I am not entirely sure how conda packaging works, but do we need to have a CPU-only version [here](https://anaconda.org/pytorch3d/pytorch3d/files) or set `USE_CUDA` flags while building?

**Comment by bottler** [comment] 2020-02-28 10:57
@raincrash MacOS is a separate issue. There are no conda packages for pytorch3d on MacOS at the moment, all the conda packages are for CUDA use with linux. 

It should be straightforward to install CPU-only from source on a mac with pip if you have pytorch, fvcore, and torchvision installed, and if you have some xcode developer tools, e.g. with `MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ pip install 'git+https://github.com/facebookresearch/pytorch3d.git'`.

We are planning to release pip binary packages for mac soon, which will make this easier.

If you have any more questions about mac, please open a separate issue.

**Comment by Hemantr05** [comment] 2020-03-17 21:54
> @Hemantr05 were you able to resolve this problem? If so, please comment with what you needed to do to resolve it so other people can also benefit! Then, please close this issue.

No, @nikhilaravi , the installation with conda failed. I guess it's because of the cuda version (requirements specify the cuda version to be 9.2 and above)

**Closed** 2020-04-24 08:51 UTC
Labels: installation

**Comment by Germanunkol** [comment] 2020-04-27 14:42
I get a similar error when trying to install with conda. I see this is closed, but not resolved...?

I've tried with python 3.6, python 3.8 and various nvidia driver and cuda versions (currently nvidia-418 and cuda-toolkit 10.1) on Ubuntu 16.04.

Note: Installing via pip works:

`pip install 'git+https://github.com/facebookresearch/pytorch3d.git'`

Conda install command:
```
$ conda install pytorch3d -c pytorch3d

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                         

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package readline conflicts for:
python=3.6 -> readline[version='7.*|>=7.0,<8.0a0|>=8.0,<9.0a0']
Package pip conflicts for:
python=3.6 -> pip
Package ld_impl_linux-64 conflicts for:
python=3.6 -> ld_impl_linux-64
Package openssl conflicts for:
python=3.6 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a']
Package ncurses conflicts for:
python=3.6 -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0']
Package fvcore conflicts for:
pytorch3d -> fvcore
Package torchvision conflicts for:
pytorch3d -> torchvision[version='>=0.5']
Package numpy conflicts for:
pytorch3d -> numpy[version='>=1.11']
Package cudatoolkit conflicts for:
pytorch3d -> cudatoolkit[version='>=10.0,<10.1|>=10.1,<10.2|>=9.2,<9.3']
Package libgcc-ng conflicts for:
python=3.6 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package zlib conflicts for:
python=3.6 -> zlib[version='>=1.2.11,<1.3.0a0']
Package pytorch conflicts for:
pytorch3d -> pytorch==1.4
Package libffi conflicts for:
python=3.6 -> libffi[version='3.2.*|>=3.2.1,<3.3a0']
Package libstdcxx-ng conflicts for:
python=3.6 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
Package sqlite conflicts for:
python=3.6 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.26.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0']
Package tk conflicts for:
python=3.6 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package six conflicts for:
pytorch3d -> six
Package xz conflicts for:
python=3.6 -> xz[version='>=5.2.3,<6.0a0|>=5.2.4,<6.0a0']
```

Installed packages:
```
$ conda list

# packages in environment at /home/user/anaconda3/envs/pytorch3d:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                1.3.0                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py36_0  
cffi                      1.14.0           py36h2e261b9_0  
chardet                   3.0.4                 py36_1003  
conda                     4.6.14                   py36_0  
cryptography              2.8              py36h1ba5d50_0  
cudatoolkit               10.1.243             h6bb024c_0  
freetype                  2.9.1                h8a8886c_1  
fvcore                    0.1.dev200325              py_0    conda-forge
idna                      2.9                        py_1  
intel-openmp              2020.0                      166  
jpeg                      9b                   h024ee3a_2  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
mkl                       2020.0                      166  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.0.15           py36ha843d7b_0  
mkl_random                1.1.0            py36hd6b4f25_0  
ncurses                   6.2                  he6710b0_0  
ninja                     1.9.0            py36hfd86e86_0  
numpy                     1.18.1           py36h4f9e942_0  
numpy-base                1.18.1           py36hde5b4d6_1  
olefile                   0.46                     py36_0  
openssl                   1.1.1g               h7b6447c_0  
pillow                    7.0.0            py36hb39fc2d_0  
pip                       20.0.2                   py36_1  
portalocker               1.7.0            py36h9f0ad1d_0    conda-forge
pycosat                   0.6.3            py36h7b6447c_0  
pycparser                 2.20                       py_0  
pyopenssl                 19.1.0                   py36_0  
pysocks                   1.7.1                    py36_0  
python                    3.6.10               hcf32534_1  
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.5.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pyyaml                    5.3.1            py36h8c4c3a4_0    conda-forge
readline                  8.0                  h7b6447c_0  
requests                  2.23.0                   py36_0  
ruamel_yaml               0.11.14          py36ha2fb22d_2  
setuptools                46.1.3                   py36_0  
six                       1.14.0                   py36_0  
sqlite                    3.31.1               h62c20be_1  
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.8                hbc83047_0  
torchvision               0.6.0                py36_cu101    pytorch
tqdm                      4.45.0             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.8                   py36_0  
wheel                     0.34.2                   py36_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.4                h516909a_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 
```

**Comment by bottler** [comment] 2020-04-27 15:01
@Germanunkol As you have a new question, it is best to open a new issue. There's no good reason to think your issue is at all related to this issue. I think your problem is a duplicate of #164.

**Comment by Germanunkol** [comment] 2020-04-28 09:43
@bottler Thanks, I posted here since the error message was similar (and #164 posted an image of the error message, so a search didn't find it), but you're right that it may be a different issue.

Anyway, it was resolved by installing through pip and git (pip install 'git+https://github.com/facebookresearch/pytorch3d.git').
