### ISSUE TITLE
double face problem

### ISSUE THREAD

**Issue by ajhamdi** [facebookresearch/pytorch3d#504] opened 2021-01-05 14:38 UTC
Some datasets (like ModelNet40) have the problem of double faces in some meshes in which the same triangle has two faces in opposite directions. This results in checkerboard rendering when using the `pytorch3d.renderer.MeshRenderer`. Please see how Pytroch3d rendering of one of these examples
![image](https://user-images.githubusercontent.com/26301932/103657952-a0116b80-4f7b-11eb-9315-e7b1a8f80e66.png)

The proper rendering should look like this (taken from Matlab-based renderer)  
![image](https://user-images.githubusercontent.com/26301932/103658106-d6e78180-4f7b-11eb-9013-6d46491a9b36.png)

Is there a way (or an option in the setting) to overcome this issue? I attached the  file which can reproduce the issue
[`.obj`](https://drive.google.com/file/d/19qcd1iWb6bY9ekekGbyctq4WoCP9XztZ/view?usp=sharing) and [`.off`](https://drive.google.com/file/d/14njomGgK7pWd-kMcgp6meDxMy2SOmK6L/view?usp=sharing)

**Comment by gkioxari** [comment] 2021-01-06 01:35
Could you please give us some code to reproduce your result with PyTorch3D? In particular, are you setting cull backfaces to False?

**Comment by ajhamdi** [comment] 2021-01-06 02:47
I am using the default option (`False`) for `cull_backfaces`, but that would not solve the issue anyway. A simple code to render is the standard rendering procedure as in the tutorials : 
```
raster_settings = RasterizationSettings(
        image_size=setup["image_size"],
        blur_radius=0.0,
        faces_per_pixel=1,
        # bin_size=None, #int
        # max_faces_per_bin=None,  # int
        # perspective_correct=False,
        # clip_barycentric_coords=None, #bool
        cull_backfaces=setup["cull_backfaces"],
    )
renderer = MeshRenderer(
        rasterizer=MeshRasterizer(cameras=camera,raster_settings=raster_settings),
        shader=HardPhongShader(device=device,cameras=camera,lights=lights)
        )

rendered_images = renderer(new_meshes, cameras=cameras, lights=lights)
    ```

**Comment by gkioxari** [comment] 2021-01-06 03:15
The correct output is the one that PyTorch3D gives. This is also the output from MeshLab. 

![Screen Shot 2021-01-05 at 7 08 20 PM](https://user-images.githubusercontent.com/4369065/103724610-97279680-4f89-11eb-951f-f2727fee1af8.png)

To get the output you are getting above with Matlab you'd have to change the mesh, in particular the faces. And effectively this is what the engine you are using is doing. It's changing the orientation of the faces. While we can consider supporting this, changing the mesh data itself when rendering is really dangerous and unscientific. Think about the gradients and how a forward/backward pass would affect your whole model. I presume here you only care about the forward pass. The right thing to do here if you want the output that you show is to manipulate your mesh data to correspond to what you want them to be. The renderer itself should not change the mesh data whatsoever nor the orientation of the faces. In pseudocode this would look like 

```python
processed_mesh = change_face_orientation(mesh)  # this op makes the faces have the same orientation, the "double" in MeshLab
img = render(processed_mesh)
```

**Comment by ajhamdi** [comment] 2021-01-06 13:00
Actually, I am using the gradients, but I can do the cleaning operation as a preprocessing step independent of the rendering. 

The problem is that there is no easy way to:
 1. figure out automatically when does this phenomenon happen ( since I am dealing with the ModelNet40 dataset and not individual instances, and this happens to about ~20%  of the instances only) 
 2. changing the face orientation of **part** of the faces that have the issue since not all faces should be flipped. 
 
I have experience in Blender and tried the built-in operations to clean the mesh, but still with no success. If I simplify the mesh using [this tool](https://github.com/HusseinBakri/BlenderPythonDecimator) from Blender, the Pytroch3d renderings would look as follows, where the double faces would be removed but the incorrect orientation remains and blacked out.
![image](https://user-images.githubusercontent.com/26301932/103771069-1e334800-5038-11eb-96fd-68e7f8e6559a.png)


The simplified mesh renders properly in Blender though! 
![image](https://user-images.githubusercontent.com/26301932/103770964-f04e0380-5037-11eb-9d32-0971a76aaec5.png)

**Comment by gkioxari** [comment] 2021-01-06 16:08
The result of the rendering is because of the shader you use. Pick a different shader, namely Gouraud. The choice of shader is important when rendering. 
I think this is an issue with your dataset so I am closing this issue.

**Closed by gkioxari** 2021-01-06 16:08 UTC
Labels: how to
