### ISSUE TITLE
ValueError: Floating point image RGB values must be in the 0..1 range.

### ISSUE THREAD

**Issue by Frank-Dz** [facebookresearch/pytorch3d#395] opened 2020-10-09 15:13 UTC
When I render some meshes. I got the following error:
```
File "render_learn.py", line 134, in <module>
    plt.imsave(os.path.join(output_path,'view%d.png'%counter), i[..., :3].cpu().numpy())
  File "/userhome/Frank/anaconda3/envs/zhiyang_py36/lib/python3.6/site-packages/matplotlib-3.3.2-py3.6-linux-x86_64.egg/matplotlib/pyplot.py", line 2251, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "/userhome/Frank/anaconda3/envs/zhiyang_py36/lib/python3.6/site-packages/matplotlib-3.3.2-py3.6-linux-x86_64.egg/matplotlib/image.py", line 1571, in imsave
    rgba = sm.to_rgba(arr, bytes=True)
  File "/userhome/Frank/anaconda3/envs/zhiyang_py36/lib/python3.6/site-packages/matplotlib-3.3.2-py3.6-linux-x86_64.egg/matplotlib/cm.py", line 314, in to_rgba
    raise ValueError("Floating point image RGB values "
ValueError: Floating point image RGB values must be in the 0..1 range.

```
My renderer setting:
```
# Imports
import torch
import os
import time
import matplotlib.pyplot as plt
from skimage.io import imread
import matplotlib
matplotlib.use('Agg')
# Util function for loading meshes
from pytorch3d.io import load_objs_as_meshes, load_obj
# Data structures and functions for rendering
from pytorch3d.structures import Meshes
# from pytorch3d.visualization import AxisArgs, plot_meshes
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    HardPhongShader,
    TexturesUV,
    TexturesVertex
)
from pytorch3d.structures.meshes import (
    Meshes,
    join_meshes_as_batch,
    join_meshes_as_scene,
)
import sys
import os
sys.path.append(os.path.abspath(''))
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")

# Set paths
DATA_DIR = "./data"

if __name__ == "__main__":
    '''
    First we set up render
    '''
    batch_size = 8
    azim = torch.linspace(0, 325, batch_size)
    R, T = look_at_view_transform(dist=1.8, azim = azim, elev =5, at=((0,-0.25, 0),))
    cameras = FoVPerspectiveCameras(device=device, R=R, T=T)
    raster_settings = RasterizationSettings(
    image_size=512, 
    blur_radius=0.0, 
    faces_per_pixel=2,  # more faces will caused GPU out of Memory.
    )
    lights = PointLights(device=device,ambient_color =((0.55, 0.55, 0.55),))
    lights.location = torch.tensor([2.0 , 300.0, 2.0], device=device)[None]
    # lights.location = torch.tensor([[0.0, 0.0, -3.0]], device=device)
    renderer = MeshRenderer(
        rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
        ),
        shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights
        )
    )
    materials = Materials(
    device=device,
    shininess=2,
    )
    print("Renderer set up.")
    
    obj_filename0 = '0.obj'
    obj_filename0 = '1.obj'
    obj_filename0 = '2.obj'
    mesh0 = load_objs_as_meshes([obj_filename0], device=device)
    mesh1 = load_objs_as_meshes([obj_filename1], device=device)
    mesh2 = load_objs_as_meshes([obj_filename2], device=device)
    texture_image0=mesh0.textures.maps_padded()
    texture_image1=mesh1.textures.maps_padded()
    texture_image2=mesh2.textures.maps_padded()
    mesh = join_meshes_as_scene([mesh0, mesh1,mesh2])
            

    meshes = mesh.extend(batch_size)
    images = renderer(meshes, cameras=cameras, lights=lights,materials = materials)
    counter = 1
    for i in images:
        plt.figure(figsize=(512, 512))
        plt.imsave('view%d.png'%counter, i[..., :3].cpu().numpy())
        plt.grid("off");
        plt.axis("off");
        plt.close()

    

```

**Comment by nikhilaravi** [comment] 2020-10-09 15:49
Closing this as it is a duplicate of #396.

**Closed by nikhilaravi** 2020-10-09 15:49 UTC
Labels: question
