### ISSUE TITLE
deform a part of the mesh

### ISSUE THREAD

**Issue by hfpro** [facebookresearch/pytorch3d#1019] opened 2022-01-05 13:27 UTC
hi, how do I transfer to the device only a part of the vertices and faces for deformation?
I want to deform a part of the grid, is it possible?

**Comment by gkioxari** [comment] 2022-01-09 20:33
Everything is possible! 

Your question is a modeling/how to question and not a bug with the library. So I am closing this issue. If you want help with your project then I would recommend moving this question to GH Discussions to get the community's support.

**Closed by gkioxari** 2022-01-09 20:33 UTC
Labels: how to
