### ISSUE TITLE
box3d_overlap gives an IoU > 1.0

### ISSUE THREAD

**Issue by jmsinusa** [facebookresearch/pytorch3d#1082] opened 2022-02-18 18:41 UTC
## 🐛 Bugs / Unexpected behaviors
3D IoU for two valid cuboids is greater than one.

## Instructions To Reproduce the Issue:
```
import numpy as np
import torch
from pytorch3d.ops import box3d_overlap
import pytorch3d
print("Pytorch3D version: ", pytorch3d.__version__)  
    # Pytorch3D version:  0.6.1

# Create two cuboids
box_a = np.array([[[-2.5629019, 4.13995749, -1.76344576], [1.92329434, 4.28127117, -1.86155124],
                   [1.86994571, 5.97489644, -1.86155124], [-2.61625053, 5.83358276, -1.76344576],
                   [-2.53123587, 4.14095496, -0.31397536], [1.95496037, 4.28226864, -0.41208084],
                   [1.90161174, 5.97589391, -0.41208084], [-2.5845845, 5.83458023, -0.31397536]]], dtype=np.float32)

box_b = np.array([[[-2.6256125, 4.13036357, -1.82893437], [1.87201008, 4.25296695, -1.82893437],
                   [1.82562476, 5.95458116, -1.82893437], [-2.67199782, 5.83197777, -1.82893437],
                   [-2.6256125, 4.13036357, -0.40095884], [1.87201008, 4.25296695, -0.40095884],
                   [1.82562476, 5.95458116, -0.40095884], [-2.67199782, 5.83197777, -0.40095884]]], dtype=np.float32)

box_a = torch.Tensor(box_a).to('cuda:0')
box_b = torch.Tensor(box_b).to('cuda:0')

# Get IoU
intersection_vol, iou_3d = box3d_overlap(box_a, box_b)
print(iou_3d.cpu().numpy()[0][0])
    # 1.1564957
```
Calculations of the volumes:
```
# Get volume of box_a and box_b
vol_a, iou_a = box3d_overlap(box_a, box_a)
print("Volume of box A:   ", vol_a.cpu().numpy()[0][0], "  IoU(A, A):", iou_a.cpu().numpy()[0][0])
vol_b, iou_b = box3d_overlap(box_b, box_b)
print("Volume of box B:   ", vol_b.cpu().numpy()[0][0], "   IoU(B, B):", iou_b.cpu().numpy()[0][0])
intersection_ab, iou_ab = box3d_overlap(box_a, box_b)
print("Intersection(A, B):", intersection_ab.cpu().numpy()[0][0], "  IoU(A, B):", iou_ab.cpu().numpy()[0][0])
union = vol_a + vol_b - intersection_ab
print("Union(A, B):       ", union.cpu().numpy()[0][0])
print("Intersection(A, B) / Union (A, B) = ", intersection_ab.cpu().numpy()[0][0], "/", union.cpu().numpy()[0][0], " = ", intersection_ab.cpu().numpy()[0][0] / union.cpu().numpy()[0][0])
```
Output:
```
Volume of box A:    11.029176   IoU(A, A): 1.0
Volume of box B:    10.93673    IoU(B, B): 1.0000001
Intersection(A, B): 11.779979   IoU(A, B): 1.1564957
Union(A, B):        10.185927
Intersection(A, B) / Union (A, B) =  11.779979 / 10.185927  =  1.1564955
```

**Comment by gkioxari** [comment] 2022-02-21 01:09
I am looking into this! This is likely a numerical issue but gotta catch it!

**Comment by gkioxari** [comment] 2022-02-21 03:27
I have found the culprit! I have published a diff that should land soon. The issue is with the `epsilon` value we define in the implementation and whose role is to check various things (e.g. points being "inside" boxes, coplanar checks etc.). That value was set to `1e-4` originally (see below for code pointers), which seems to be too large for your test case, where boxes have coordinates that are really close to each other. If you set the value below to `1e-5` instead of `1e-4`, the output `iou` is around 0.91.

For CUDA: https://github.com/facebookresearch/pytorch3d/blob/59972b121d8c7bfc0e156b5ad5fcd77c11874178/pytorch3d/csrc/iou_box3d/iou_utils.cuh#L15

For C++: https://github.com/facebookresearch/pytorch3d/blob/59972b121d8c7bfc0e156b5ad5fcd77c11874178/pytorch3d/csrc/iou_box3d/iou_utils.h#L21

**Comment by gkioxari** [comment] 2022-02-21 17:55
The fix has landed https://github.com/facebookresearch/pytorch3d/commit/3de41223dde5facc3ba5c445e2cb11e6b4410d6d

**Closed by gkioxari** 2022-02-21 17:55 UTC

**Comment by ffent** [comment] 2023-11-12 10:04
Hi @gkioxari, even after the fix I encountered the same issue as @jmsinusa but with different box corner values.

### Instructions To Reproduce the Issue:
```
import numpy as np
import torch
from pytorch3d.ops import box3d_overlap
import pytorch3d
print("Pytorch3D version: ", pytorch3d.__version__)  
    # Pytorch3D version:  0.7.5

# Create two cuboids
box_a = np.array([[[19.7804, -4.8337, -1.2441],
                   [24.3597, -4.8431, -1.2441],
                   [24.3648, -2.3689, -1.2441],
                   [19.7855, -2.3595, -1.2441],
                   [19.7804, -4.8337,  0.8192],
                   [24.3597, -4.8431,  0.8192],
                   [24.3648, -2.3689,  0.8192],
                   [19.7855, -2.3595,  0.8192]]], dtype=np.float32)

box_b = np.array([[[19.8159, -4.8659, -1.2500],
                   [24.4267, -4.8794, -1.2500],
                   [24.4341, -2.3641, -1.2500],
                   [19.8233, -2.3506, -1.2500],
                   [19.8159, -4.8659,  0.8500],
                   [24.4267, -4.8794,  0.8500],
                   [24.4341, -2.3641,  0.8500],
                   [19.8233, -2.3506,  0.8500]]], dtype=np.float32)

box_a = torch.Tensor(box_a).to('cuda:0')
box_b = torch.Tensor(box_b).to('cuda:0')

# Get IoU
intersection_vol, iou_3d = box3d_overlap(box_a, box_b)
print(iou_3d.cpu().numpy()[0][0])
    # 1.23788
```

Calculations of the volumes:
```
# Get volume of box_a and box_b
vol_a, iou_a = box3d_overlap(box_a, box_a)
print("Volume of box A:   ", vol_a.cpu().numpy()[0][0], "  IoU(A, A):", iou_a.cpu().numpy()[0][0])
vol_b, iou_b = box3d_overlap(box_b, box_b)
print("Volume of box B:   ", vol_b.cpu().numpy()[0][0], "   IoU(B, B):", iou_b.cpu().numpy()[0][0])
intersection_ab, iou_ab = box3d_overlap(box_a, box_b)
print("Intersection(A, B):", intersection_ab.cpu().numpy()[0][0], "  IoU(A, B):", iou_ab.cpu().numpy()[0][0])
union = vol_a + vol_b - intersection_ab
print("Union(A, B):       ", union.cpu().numpy()[0][0])
print("Intersection(A, B) / Union (A, B) = ", intersection_ab.cpu().numpy()[0][0], "/", union.cpu().numpy()[0][0], " = ", intersection_ab.cpu().numpy()[0][0] / union.cpu().numpy()[0][0])
```

Output:
```
Volume of box A:    23.377499   IoU(A, A): 0.9999997
Volume of box B:    24.35505    IoU(B, B): 0.9999997
Intersection(A, B): 26.403193   IoU(A, B): 1.23788
Union(A, B):        21.329355
Intersection(A, B) / Union (A, B) =  26.403193 / 21.329355  =  1.2378805
```

**Comment by ffent** [comment] 2025-07-09 15:52
Is there any update on this?
