### ISSUE TITLE
Wrong box3d_overlap output

### ISSUE THREAD

**Issue by mikeedi** [facebookresearch/pytorch3d#992] opened 2021-12-13 20:54 UTC
Strange behaviour of pytorch3d.ops.box3d_overlap  

First case - zero overlap expected, but non-zero value is returned (and also different values depending on the order of the arguments):
```
import torch
from pytorch3d.ops import box3d_overlap
a = torch.tensor([[-1.0000, -1.0000, -0.5000],
        [ 1.0000, -1.0000, -0.5000],
        [ 1.0000,  1.0000, -0.5000],
        [-1.0000,  1.0000, -0.5000],
        [-1.0000, -1.0000,  0.5000],
        [ 1.0000, -1.0000,  0.5000],
        [ 1.0000,  1.0000,  0.5000],
        [-1.0000,  1.0000,  0.5000]])
b = torch.tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

print(box3d_overlap(a[None], b[None]))
print(box3d_overlap(b[None], a[None]))
```
Returns:
```
(tensor([[4.0000]]), tensor([[inf]]))
(tensor([[0.]]), tensor([[0.]]))
```

Second case:
```
import torch
from pytorch3d.ops import box3d_overlap
# function from https://github.com/facebookresearch/pytorch3d/blob/main/tests/test_iou_box3d.py 
def create_box(xyz, whl):
    x, y, z = xyz
    w, h, le = whl

    verts = torch.tensor(
        [
            [x - w / 2.0, y - h / 2.0, z - le / 2.0],
            [x + w / 2.0, y - h / 2.0, z - le / 2.0],
            [x + w / 2.0, y + h / 2.0, z - le / 2.0],
            [x - w / 2.0, y + h / 2.0, z - le / 2.0],
            [x - w / 2.0, y - h / 2.0, z + le / 2.0],
            [x + w / 2.0, y - h / 2.0, z + le / 2.0],
            [x + w / 2.0, y + h / 2.0, z + le / 2.0],
            [x - w / 2.0, y + h / 2.0, z + le / 2.0],
        ],
        device=xyz.device,
        dtype=torch.float32,
    )
    return verts


ctrs = torch.tensor([[0., 0., 0.], [-1., 1., 0.]])
whl = torch.tensor([[2., 2., 2.], [2., 2, 2]])
box8a = create_box(ctrs[0], whl[0])
box8b = create_box(ctrs[1], whl[1])
print(box3d_overlap(box8a[None], box8b[None]))
```
Returns:
```
(tensor([[1.3704]]), tensor([[0.0937]]))
```
if you calculate the overlap area by hand, you get exactly 2, but the function gives a different result.

Moreover, if you slightly change the values, then the answer will be correct:
```
ctrs = torch.tensor([[0., 0., 0.], [-0.999999, 1., 0.]])
whl = torch.tensor([[2., 2., 2.], [2., 2, 2]])
box8a = create_box(ctrs[0], whl[0])
box8b = create_box(ctrs[1], whl[1])
print(box3d_overlap(box8a[None], box8b[None]))

ctrs = torch.tensor([[0., 0., 0.], [-1., 1., 0.]])
whl = torch.tensor([[2., 2., 2.], [2., 2, 2]])
box8a = create_box(ctrs[0], whl[0])
box8b = create_box(ctrs[1], whl[1])
print(box3d_overlap(box8a[None], box8b[None]))

ctrs = torch.tensor([[0., 0., 0.], [-1.000001, 1., 0.]])
whl = torch.tensor([[2., 2., 2.], [2., 2, 2]])
box8a = create_box(ctrs[0], whl[0])
box8b = create_box(ctrs[1], whl[1])
print(box3d_overlap(box8a[None], box8b[None]))
```
Returns:
```
(tensor([[2.0002]]), tensor([[0.1429]]))
(tensor([[1.3704]]), tensor([[0.0937]]))
(tensor([[1.9998]]), tensor([[0.1428]]))
```

Was checked with
```
torch == 1.6.0+cu101
pytorch3d==0.6.1
```

**Comment by nikhilaravi** [comment] 2021-12-16 13:55
@mikeedi thanks for raising this issue. I think this might be due to the setting of an epsilon value. We will look into it!

**Comment by gkioxari** [comment] 2021-12-16 15:50
Thank you for bringing this up!

In the first case, the second box has all its vertices at (0,0,0) which is an invalid box. We should likely check for this as the algorithm will not handle this gracefully. We check that boxes have coplanar points in the sides, but we should check that the area of the planes is nonzero. 

The second case should work and it's a mystery why it doesn't. Our tests have similar box configurations. We will look into that.

**Comment by lysukhin** [comment] 2021-12-17 11:31
Hi, @nikhilaravi @gkioxari !

I got some confusing results to report as well concerning box 3d overlap.
I wrote some custom tests and found out that iou3d of a unit box at the origin with itself is not always equal to 1 (not even close to it sometimes). 

Even more confusing is the fact that the chance of a 'wrong' self-IoU is different for CPU (about 5% of the time, see code below) and GPU (about 30%).

Code for reproducing:

```
import torch
import numpy as np
import tqdm

from pytorch3d.ops import box3d_overlap


num_random_runs = 10000
max_diff = 1e-2

# device = "cpu"
device = "cuda:0"


def rotation_matrix_around_y(yaw):
    cos_yaw = np.cos(yaw)
    sin_yaw = np.sin(yaw)
    return np.asarray([
        [cos_yaw,   0,  sin_yaw],
        [0,         1,        0],
        [-sin_yaw,  0,  cos_yaw]
    ])


def main():

    x = y = z = 0.
    l = w = h = 1.

    x_corners = np.asarray([-1, 1, 1, -1, -1, 1, 1, -1], dtype=np.float32) * l / 2
    y_corners = np.asarray([-1, -1, 1, 1, -1, -1, 1, 1], dtype=np.float32) * h / 2
    z_corners = np.asarray([-1, -1, -1, -1, 1, 1, 1, 1], dtype=np.float32) * w / 2
    _corners = np.stack((x_corners, y_corners, z_corners), axis=1)  # -> 8 x 3
    shift = np.asarray([x, y, z], dtype=np.float32)[None, :]

    ious = []
    yaws = []
    for i in tqdm.trange(num_random_runs):
        yaw = np.random.uniform(-np.pi, np.pi)

        corners = (rotation_matrix_around_y(yaw) @ _corners.T).T
        corners += shift
        corners = torch.from_numpy(corners).float().unsqueeze(0).to(device)

        vol, iou = box3d_overlap(corners, corners)
        ious.append(iou.item())
        yaws.append(yaw)

    correct = 0
    for yaw, iou in zip(yaws, ious):

        if abs(iou - 1.) < max_diff:
            correct += 1
        # else:
        #     print(yaw, iou)

    print("% of correct self-IoU3d:", correct / num_random_runs)


if __name__ == "__main__":
    main()
```

**Comment by gkioxari** [comment] 2021-12-18 00:19
This is now fixed with https://github.com/facebookresearch/pytorch3d/commit/ccfb72cc502cc3fe30e168fcd220791ee8e449a2

For the first case, we check to see if the sides of the input boxes have non zero area. 

The second case was a tricky one and it boiled down to a numerical issue which is fixed by a small change in the algorithm. It's a nuance so I won't get into too much detail but it resulted from the fact that your two input boxes had coplanar sides. This is why when you slightly perturbed the center of the box, the output was correct. I didn't catch this case when I implemented this so thank you very much for bringing this up and giving us reproducible code. Let us know if you have any more issues with it!

**Comment by gkioxari** [comment] 2021-12-18 03:07
@lysukhin
I ran your code and I found it to always be 1.0 for all runs, for cuda and cpu. What version are you using? Could you update to master and check again?

**Comment by lysukhin** [comment] 2021-12-18 09:41
@gkioxari 
Thanks for your answer, but that's interesting:
I re-ran your version of code and got `[False] 6.09%` for `cpu` and `[False] 32.16%` for `cuda:0`.
Moreover, I frequently face `ValueError: Plane vertices are not coplanar` while using `cuda:0` (and never for `cpu` in my experiments).

Output of `pytorch3d.__version__` is `0.6.0`.

**UPD**: 
After re-installing `pytorch3d` via `conda` (which resulted in version `0.6.1`) results for both `cpu` and `cuda:0` became OK. Not sure if further investigation is required, but thanks for your time anyway @gkioxari @nikhilaravi

**Comment by gkioxari** [comment] 2021-12-18 18:35
@lysukhin 
The check for coplanar has an exposed `eps` value which you could increase. It's set by default to 1e-4.

https://github.com/facebookresearch/pytorch3d/blob/315f2487db91e32b5e36fd547b278ac0a22f7081/pytorch3d/ops/iou_box3d.py#L48

**Comment by gkioxari** [comment] 2021-12-18 18:36
I closed this issue but feel free to re-open it.

**Closed** 2021-12-18 18:36 UTC
Labels: bug

**Comment by Leozyc-waseda** [comment] 2022-06-23 02:38
> Moreover, I frequently face ValueError: Plane vertices are not coplanar while using cuda:0 (and never for cpu in my experiments).


same error.And I found that using cuda is very slow, usually about 1 second, but cpu does not have this problem. .

```
box_compare
 tensor([[[ 4.1103, -6.5861, -0.6426],
         [ 4.0670, -4.9307, -0.5413],
         [ 4.0647, -4.8449, -1.9441],
         [ 4.1081, -6.5004, -2.0454],
         [ 8.3924, -6.4740, -0.6426],
         [ 8.3490, -4.8185, -0.5413],
         [ 8.3468, -4.7328, -1.9441],
         [ 8.3901, -6.3883, -2.0454]]], device='cuda:0')
box_gt 
 tensor([[[ 4.1092, -6.5426, -0.5906],
         [ 4.0657, -4.8840, -0.5906],
         [ 4.0657, -4.8840, -2.0670],
         [ 4.1092, -6.5426, -2.0670],
         [ 8.8965, -6.4172, -0.5906],
         [ 8.8531, -4.7586, -0.5906],
         [ 8.8531, -4.7586, -2.0670],
         [ 8.8965, -6.4172, -2.0670]]], device='cuda:0')
 
box_compare =torch.Tensor(box_compare).to("cuda:0")
box_gt = torch.Tensor(box_gt).to("cuda:0")
print("box_compare\n",box_compare)
print("box_gt \n",box_gt)
intersection_vol, iou_3d = box3d_overlap(box_compare, box_gt)
print('Get IoU :',iou_3d.cpu().numpy()[0][0])   
                   
```

after delete .to("cuda:0"), runs very smoothly.
Is there something wrong?

**Comment by gkioxari** [comment] 2022-08-10 13:42
Just saw this! We have already exposed `eps` for coplanar checks

https://github.com/facebookresearch/pytorch3d/blob/276c9a8acbfa715f5802f26ec9f4141bde26ecb4/pytorch3d/ops/iou_box3d.py#L111-L113

**Comment by AOOOOOA** [comment] 2023-06-06 09:36
> Just saw this! We have already exposed `eps` for coplanar checks
> 
> https://github.com/facebookresearch/pytorch3d/blob/276c9a8acbfa715f5802f26ec9f4141bde26ecb4/pytorch3d/ops/iou_box3d.py#L111-L113

Hi I tried this but it doesn't work. My bbox value is shown below:

`bbox A: 
[[2.50547760e+02 1.31224823e+02 2.72669317e-03]
 [2.50547760e+02 1.31224823e+02 2.72669317e-03]
 [2.50547760e+02 1.31658722e+02 2.72669317e-03]
 [2.50547760e+02 1.31658722e+02 2.72669317e-03]
 [2.58746643e+02 1.31224823e+02 2.72669317e-03]
 [2.58746643e+02 1.31224823e+02 2.72669317e-03]
 [2.58746643e+02 1.31658722e+02 2.72669317e-03]
 [2.58746643e+02 1.31658722e+02 2.72669317e-03]]

bbox B: 
[[ 2.73294769e+02  1.30493774e+02 -1.93447247e-03]
 [ 2.73294769e+02  1.30493774e+02  1.52289891e+00]
 [ 2.73294769e+02  1.28486954e+02 -1.93447247e-03]
 [ 2.73294769e+02  1.28486954e+02  1.52289891e+00]
 [ 2.68781250e+02  1.30493790e+02 -1.93447247e-03]
 [ 2.68781250e+02  1.30493790e+02  1.52289891e+00]
 [ 2.68781250e+02  1.28486969e+02 -1.93447247e-03]
 [ 2.68781250e+02  1.28486969e+02  1.52289891e+00]]
`
